from enum import Enum


class OrderFillReason(str, Enum):
    LIMIT_ORDER = "LIMIT_ORDER"
    MARKET_IF_TOUCHED_ORDER = "MARKET_IF_TOUCHED_ORDER"
    MARKET_ORDER = "MARKET_ORDER"
    MARKET_ORDER_DELAYED_TRADE_CLOSE = "MARKET_ORDER_DELAYED_TRADE_CLOSE"
    MARKET_ORDER_MARGIN_CLOSEOUT = "MARKET_ORDER_MARGIN_CLOSEOUT"
    MARKET_ORDER_POSITION_CLOSEOUT = "MARKET_ORDER_POSITION_CLOSEOUT"
    MARKET_ORDER_TRADE_CLOSE = "MARKET_ORDER_TRADE_CLOSE"
    STOP_LOSS_ORDER = "STOP_LOSS_ORDER"
    STOP_ORDER = "STOP_ORDER"
    TAKE_PROFIT_ORDER = "TAKE_PROFIT_ORDER"
    TRAILING_STOP_LOSS_ORDER = "TRAILING_STOP_LOSS_ORDER"

    def __str__(self) -> str:
        return str(self.value)
