# Copyright 2024 Takin Profit. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: Build Oanda Client
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        node-version: [20]

    steps:
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Set up UV
      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Set up pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      # Make build script executable
      - name: Make scripts executable
        run: |
          chmod +x ./build.sh
          chmod +x ./gen.sh

      # Install dependencies and build
      - name: Build package
        run: ./build.sh build

      # Optional: Publish to PyPI (only on tagged releases)
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: ./build.sh publish
